/* The schedule lives in one place so every event page stays up to date. */
const weddingEvents = [
  {
    id: "outbound-train",
    day: "27 Dec",
    date: "Sunday, 27 December 2026",
    time: "7:10 AM",
    title: "The journey begins",
    venue: "Secunderabad Jn Railway Station",
    category: "journey",
    summary: "We set off together for Bhopal on Train 22691",
    details: ["<strong>Train number:</strong> 22691", "<strong>Boarding time:</strong> 7:10 AM", "<strong>Coach number:</strong> To be announced", "<strong>Seat numbers:</strong> To be announced"],
    map: "https://maps.app.goo.gl/dSaFnCo6ekKPRaWr9",
    mapLabel: "Open Secunderabad Jn map"
  },
  {
    id: "bhopal-arrival",
    day: "27 Dec",
    date: "Sunday, 27 December 2026",
    time: "8:55 PM",
    title: "Welcome to Bhopal",
    venue: "Bhopal Jn Railway Station",
    category: "journey",
    summary: "Train 22691 reaches Bhopal Jn at 8:55 PM. Rooms will be ready for check-in from 9:00 PM",
    details: ["<strong>Arrival station:</strong> Bhopal Jn", "<strong>Arrival time:</strong> 8:55 PM", "<strong>Rooms check-in:</strong> from 9:00 PM", "<strong>Resort details:</strong> Fortune Resort & Gardens"],
    map: "https://maps.app.goo.gl/MjPHqGioGqBx4mKu5",
    mapLabel: "Open Bhopal Jn map"
  },
  {
    id: "check-in",
    day: "27 Dec",
    date: "Sunday, 27 December 2026",
    time: "9:00 PM onwards",
    title: "Rooms check-in",
    venue: "Fortune Resort & Gardens, Bhopal",
    category: "welcome",
    summary: "Settle in, freshen up, and get ready for three wonderful days together",
    details: ["<strong>Resort Name:</strong> Fortune Resort & Gardens", "<strong>Address:</strong> Bairagarh Kalan, Bairagarh, Bhopal – 462030, Madhya Pradesh", "<strong>Room allocation:</strong> To be announced", "<strong>Reception desk details:</strong> To be announced"],
    map: "https://maps.app.goo.gl/9rPVQdmpCpWCATGD6",
    mapLabel: "Open Fortune Resort & Gardens map"
  },
  {
    id: "breakfast-28",
    day: "28 Dec",
    date: "Monday, 28 December 2026",
    time: "8:30 AM",
    title: "Breakfast",
    venue: "Banquet hall dining area",
    category: "dining",
    summary: "A relaxed breakfast before the festivities begin",
    details: ["<strong>Dress code:</strong> To be announced", "<strong>Please arrive on time so the day can begin together</strong>"],
  },
  {
    id: "haldi-carnival",
    day: "28 Dec",
    date: "Monday, 28 December 2026",
    time: "10:00 AM",
    title: "Haldi Carnival",
    venue: "Pool side",
    category: "haldi",
    summary: "Sunshine, laughter, and a joyful splash of haldi by the pool",
    details: ["<strong>Event theme:</strong> To be announced", "<strong>Dress code:</strong> To be announced", "<strong>Event/ Program details:</strong> To be announced"],
  },
  {
    id: "lunch-28",
    day: "28 Dec",
    date: "Monday, 28 December 2026",
    time: "1:00 PM",
    title: "Lunch",
    venue: "Banquet hall dining area",
    category: "dining",
    summary: "A delicious break between the day's celebrations",
    details: ["<strong>Dress code:</strong> To be announced", "<strong>Please arrive on time</strong>"],
  },
  {
    id: "mehendi",
    day: "28 Dec",
    date: "Monday, 28 December 2026",
    time: "3:00 PM",
    title: "Mehendi Ceremony",
    venue: "Pool side",
    category: "mehendi",
    summary: "An afternoon of intricate henna, music, and warm conversations",
    details: ["<strong>Event theme:</strong> To be announced", "<strong>Dress code:</strong> To be announced", "<strong>Event/ Program details:</strong> To be announced"],
  },
  {
    id: "sangeet",
    day: "28 Dec",
    date: "Monday, 28 December 2026",
    time: "7:00 PM",
    title: "Sangeet followed by Dinner",
    venue: "Banquet hall",
    category: "sangeet",
    summary: "An evening of music, dance, celebration, and dinner under glittering lights",
    details: ["<strong>Dinner will be served during the Sangeet function</strong>", "<strong>Event theme:</strong> To be announced", "<strong>Dress code:</strong> To be announced", "<strong>Event/ Performance details:</strong> To be announced"],
  },
  {
    id: "breakfast-29",
    day: "29 Dec",
    date: "Tuesday, 29 December 2026",
    time: "8:30 AM",
    title: "Breakfast",
    venue: "Banquet hall dining area",
    category: "dining",
    summary: "Begin the second day of celebrations over breakfast",
    details: ["<strong>Dress code:</strong> To be announced", "<strong>Please arrive on time</strong>"],
  },
  {
    id: "varapooja",
    day: "29 Dec",
    date: "Tuesday, 29 December 2026",
    time: "10:30 AM",
    title: "Varapooja / Phal Daan",
    venue: "Banquet hall",
    category: "pooja",
    summary: "A meaningful ceremony bringing both families together",
    details: ["<strong>Event theme:</strong> To be announced", "<strong>Dress code:</strong> To be announced", "<strong>Event/ Program details:</strong> To be announced"],
  },
  {
    id: "lunch-29",
    day: "29 Dec",
    date: "Tuesday, 29 December 2026",
    time: "1:00 PM",
    title: "Lunch",
    venue: "Banquet hall dining area",
    category: "dining",
    summary: "Let's enjoy a delicious afternoon before the evening celebrations begin",
    details: ["<strong>Dress code:</strong> To be announced", "<strong>Please arrive on time</strong>"],
  },
  {
    id: "baraat",
    day: "29 Dec",
    date: "Tuesday, 29 December 2026",
    time: "5:00 PM",
    title: "Baraat Procession",
    venue: "Main entrance of the resort",
    category: "baraat",
    summary: "The celebration unfolds in a vibrant symphony of music, colour, laughter, and unforgettable moments",
    details: ["<strong>Event theme:</strong> To be announced", "<strong>Dress code:</strong> To be announced", "<strong>Event/ Program details:</strong> To be announced"],
  },
  {
    id: "reception",
    day: "29 Dec",
    date: "Tuesday, 29 December 2026",
    time: "7:00 PM",
    title: "Reception followed by Dinner",
    venue: "Open sky lawn",
    category: "reception",
    summary: "An open-air evening celebrating the togetherness of Rohit and Shreya, followed by a delightful dinner",
    details: ["<strong>Dinner will be served during the reception function</strong>", "<strong>Event theme:</strong> To be announced", "<strong>Dress code:</strong> To be announced", "<strong>Event/ Program details:</strong> To be announced"],
  },
  {
    id: "kashi-yatra",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "6:00 AM",
    title: "Kashi Yatra & Gauri Pooja",
    venue: "Marriage banquet hall",
    category: "pooja",
    summary: "The wedding day begins with cherished rituals and blessings",
    details: ["<strong>Event theme:</strong> To be announced", "<strong>Dress code:</strong> To be announced", "<strong>Event/ Program details:</strong> To be announced", "<strong>Please arrive a few minutes early for the rituals</strong>"],
  },
  {
    id: "muhurtam",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "7:55 AM",
    title: "Jeelakara Bellam Muhurtam",
    venue: "Marriage banquet hall",
    category: "muhurtam",
    summary: "The auspicious moment when Rohit and Shreya begin their new chapter together",
    details: ["<strong>Muhurtam:</strong> 7:55 AM IST", "<strong>Dress code:</strong> To be announced", "<strong>Event/ Program details:</strong> To be announced", "<strong>Please be seated before the ceremony begins</strong>"],
  },
  {
    id: "breakfast-30",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "8:30 AM",
    title: "Breakfast",
    venue: "Banquet hall dining area",
    category: "dining",
    summary: "Take a moment to relax and enjoy a delightful breakfast before the celebrations continue",
    details: ["<strong>Dress code:</strong> To be announced", "<strong>Please arrive on time</strong>"],
  },
  {
    id: "homam",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "9:00 AM",
    title: "Homam & Lakshmi Pooja",
    venue: "Banquet hall",
    category: "pooja",
    summary: "A beautiful morning where sacred traditions, heartfelt blessings, and the promise of forever come together",
    details: ["<strong>Event theme:</strong> To be announced", "<strong>Dress code:</strong> To be announced", "<strong>Event/ Program details:</strong> To be announced"],
  },
  {
    id: "lunch-30",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "1:00 PM",
    title: "Lunch",
    venue: "Banquet hall dining area",
    category: "dining",
    summary: "A delightful farewell meal before check-out and the journey home",
    details: ["<strong>Dress code:</strong> To be announced", "<strong>Please arrive on time</strong>"],
  },
  {
    id: "checkout",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "4:00 PM",
    title: "Rooms check-out",
    venue: "Heading back home",
    category: "welcome",
    summary: "Please complete room check-out before the return journey",
    details: ["<strong>Check-out time:</strong> 4:00 PM", "<strong>Luggage coordination:</strong> To be announced"],
  },
  {
    id: "return-train",
    day: "30 Dec",
    date: "Wednesday, 30 December 2026",
    time: "9:00 PM",
    title: "Journey home",
    venue: "Bhopal Jn Railway Station",
    category: "journey",
    summary: "We board Train 12589 for the journey back to Charlapalli/ Cherlapally",
    details: ["<strong>Train number:</strong> 12589", "<strong>Departure time:</strong> 9:00 PM", "<strong>Coach number:</strong> To be announced", "<strong>Seat numbers:</strong> To be announced"],
    map: "https://maps.app.goo.gl/MjPHqGioGqBx4mKu5",
    mapLabel: "Open Bhopal Jn map"
  },
  {
    id: "Charlapalli/ Cherlapally - arrival",
    day: "31 Dec",
    date: "Thursday, 31 December 2026",
    time: "1:30 PM",
    title: "Until we meet again",
    venue: "Charlapalli/ Cherlapally Railway Station",
    category: "journey",
    summary: "Train 12589 arrives at Charlapalli/ Cherlapally, marking the perfect conclusion to our wedding celebrations",
    details: ["<strong>Arrival station:</strong> Charlapalli/ Cherlapally Railway Station", "<strong>Arrival time:</strong> 1:30 PM", "<strong>Thank you for being part of our celebrations</strong>"],
    map: "https://maps.app.goo.gl/GBfrULoSmMxC1pWL6",
    mapLabel: "Open Charlapalli/ Cherlapally station map"
  }
];

const eventThemes = {
  journey: { label: "Train journey", symbol: "🚆" },
  welcome: { label: "A warm welcome", symbol: "⌂" },
  dining: { label: "Food & fellowship", symbol: "🍽" },
  haldi: { label: "Sunlit celebration", symbol: "☀" },
  mehendi: { label: "Henna & harmony", symbol: "❋" },
  sangeet: { label: "Music & dance", symbol: "♫" },
  pooja: { label: "Sacred ritual", symbol: "◌" },
  baraat: { label: "Joy in motion", symbol: "✹" },
  reception: { label: "An evening together", symbol: "✧" },
  muhurtam: { label: "The auspicious hour", symbol: "❈" }
};
